#!/bin/bash
#save in a directory(example: /bin/) of PATH (Terminal: "echo $PATH")
#usage: homekit -a
NOCOLOR='\033[0m'       # ${NOCOLOR}
RED='\033[0;31m'        # ${RED}
ORANGE='\033[0;33m'     #	${ORANGE}
GREEN='\033[0;32m'      #	${GREEN}

export SDK_PATH="~/git/homekit/esp-open-rtos/"

export ESPPORT=/dev/tty.SLAB_USBtoUART
#export ESPPORT=/dev/tty.usbserial-1D1120
#export ESPPORT=/dev/tty.usbserial-1D1130
#export ESPPORT=/dev/tty.usbserial-1D1140
#export ESPPORT=/dev/tty.usbserial-1A1240

NAME=${PWD##*/}

while getopts ":efmhrx" opt; do
  case $opt in
    r)
      echo -e "${GREEN}remove build/firmware folders${NOCOLOR}"
      rm -R ./build
      rm -R ./firmware
      echo -e "${ORANGE}building project${NOCOLOR}"
      cd ../../
      docker run -it --rm -v "$(pwd)":/project -w /project esp-rtos make -C amaider_examples/$NAME all
      ;;
    e)
      echo -e "${ORANGE}erase flash${NOCOLOR}"
      make -C ../../amaider_examples/$NAME erase_flash
      exit
      ;;
    f)
      echo -e "${ORANGE}flash with monitor${NOCOLOR}"
      make -C ../../amaider_examples/$NAME flash monitor
      ;;
    m)
      echo -e "${ORANGE}monitor${NOCOLOR}"
      make -C ../../amaider_examples/$NAME monitor
      ;;
    h)
      echo -e "${ORANGE}nano /bin/homekit/${NOCOLOR}"
      nano /bin/homekit/
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done